/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.CRUDUSUARIO;
import Clases.CRUDUnidad;
import Clases.Limpiar;
import Clases.Unidad;
import Clases.Usuario;
import Conexion.Database;
import Tablas.Tabla_Usuario;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Raul
 */
public class adminUsuarios extends javax.swing.JFrame {

    static Login home = new Login();
    Tabla_Usuario usu = new Tabla_Usuario();
    Limpiar lim = new Limpiar();
    CRUDUSUARIO crud_usu;
    int Clic_tabla = 0;

    
    public adminUsuarios() {
        initComponents();
        usu.visualizar_Usuario(tblUsuarios);
        //mostrarUsuarios();
        //habilitacionDeTextos(false);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        activa_boton(false, false, true);
        tblUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setResizable(false);
        
    }

   
    
    public void modificar() {
        int errores = 0;
        if (txtRut.getText().equals("") || txtNombre.getText().equals("") || txtPass.getText().equals("")
            || txtPaterno.getText().equals("") || txtUnidad.getText().equals("") || txtMaterno.getText().equals("") ||
                txtNacionalidad.getText().equals("")|| txtTipoUsuario.getText().equals("")||txtHabilitado.getText().equals("")
                || dtFecha.getDate().equals("")||txtMail.getText().equals("")|| txtFono.getText().equals("")) {
            errores = errores + 1;
        }

        if (errores >= 1) {
            JOptionPane.showMessageDialog(null, "Falta información, rellene los campos", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            crud_usu = new CRUDUSUARIO();
            Usuario usu = new Usuario();
            usu.setRut(txtRut.getText());
            usu.setPass(txtPass.getText());
            usu.setCorreo(txtMail.getText());
            usu.setFechaIngreso(dtFecha.getDate());
            usu.setFono(txtFono.getText());
            usu.setHabilitado(Integer.parseInt(txtHabilitado.getText().toString()));
            usu.setId_tipoUsuario(Integer.parseInt(txtTipoUsuario.getText().toString()));
            usu.setId_Unidad(Integer.parseInt(txtUnidad.getText()));
            usu.setMaterno(txtMaterno.getText());
            usu.setPaterno(txtPaterno.getText());
            usu.setNombre(txtNombre.getText());
            usu.setNacionalidad(txtNacionalidad.getText());
            
            
            

            crud_usu.Modificar_Usuario(usu);
        }

    }

    public void activa_boton(boolean a1, boolean a2, boolean a3) {
        btnModificar.setEnabled(a1);
        btnHabilita.setEnabled(a2);
        txtRut.setEnabled(a3);
    }    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblNacionalidad = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPaterno = new javax.swing.JLabel();
        lblMaterno = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();
        lblHabilitado = new javax.swing.JLabel();
        lblTituloInicial = new javax.swing.JLabel();
        lblTipoUsuario = new javax.swing.JLabel();
        lblUnidad = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPaterno = new javax.swing.JTextField();
        txtMaterno = new javax.swing.JTextField();
        txtMail = new javax.swing.JTextField();
        txtFono = new javax.swing.JTextField();
        txtNacionalidad = new javax.swing.JTextField();
        txtTipoUsuario = new javax.swing.JTextField();
        txtUnidad = new javax.swing.JTextField();
        txtHabilitado = new javax.swing.JTextField();
        dtFecha = new com.toedter.calendar.JDateChooser();
        btnModificar = new javax.swing.JButton();
        btnHabilita = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administracion de Usuarios");

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUsuarios);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        lblNacionalidad.setText("Nacionalidad");

        lblClave.setText("Clave");

        lblNombre.setText("Nombre");

        lblPaterno.setText("Paterno");

        lblMaterno.setText("Materno");

        lblFechaIngreso.setText("Fecha Ingreso");

        lblMail.setText("Mail");

        lblFono.setText("Fono");

        lblHabilitado.setText("Habilitado");

        lblTituloInicial.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloInicial.setText("Descripción usuario");

        lblTipoUsuario.setText("Tipo Usuario");

        lblUnidad.setText("Unidad");

        jLabel2.setText("Rut");

        dtFecha.setDateFormatString("yyyy-MM-dd");
        dtFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dtFechaFocusLost(evt);
            }
        });

        btnModificar.setText("Modificar");

        btnHabilita.setText("Habilitar/Bloquear");
        btnHabilita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHabilitaActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTituloInicial)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaterno))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblPaterno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPaterno))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFechaIngreso)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(lblClave)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30)
                                        .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTipoUsuario)
                                    .addComponent(lblUnidad)
                                    .addComponent(lblHabilitado))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTipoUsuario)
                                    .addComponent(txtUnidad)
                                    .addComponent(txtHabilitado)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblNacionalidad)
                                .addGap(18, 18, 18)
                                .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMail)
                                    .addComponent(lblFono))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFono)
                                    .addComponent(txtMail))))))
                .addGap(79, 79, 79))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnModificar)
                .addGap(18, 18, 18)
                .addComponent(btnHabilita, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNacionalidad)
                            .addComponent(jLabel2)
                            .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClave)
                            .addComponent(lblTipoUsuario)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblUnidad)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPaterno)
                            .addComponent(txtPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHabilitado)
                            .addComponent(txtHabilitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMaterno)
                            .addComponent(txtMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMail)
                            .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblFechaIngreso)
                            .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFono)
                        .addComponent(txtFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnHabilita)
                    .addComponent(btn_salir))
                .addGap(79, 79, 79))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        Clic_tabla = this.tblUsuarios.rowAtPoint(evt.getPoint());
        Date dateI = null;
        String fechaI;
        dateI = dtFecha.getDate();
        fechaI =dateI.toString() + tblUsuarios.getValueAt(Clic_tabla, 5);
        String rut = "" + tblUsuarios.getValueAt(Clic_tabla, 0);
        String pass = "" + tblUsuarios.getValueAt(Clic_tabla, 1);
        String nombre = ""+ tblUsuarios.getValueAt(Clic_tabla, 2);
        String paterno = ""+ tblUsuarios.getValueAt(Clic_tabla, 3);
        String materno = ""+ tblUsuarios.getValueAt(Clic_tabla, 4);
       //Date fechaIngreso = "" + tblUsuarios.getValueAt(Clic_tabla, 5);
        String hab = ""+ tblUsuarios.getValueAt(Clic_tabla, 6);
        String nacionalidad = ""+ tblUsuarios.getValueAt(Clic_tabla, 7);
        String mail = ""+ tblUsuarios.getValueAt(Clic_tabla, 8);
        String fono = ""+ tblUsuarios.getValueAt(Clic_tabla, 9);
        String tipousuario = ""+ tblUsuarios.getValueAt(Clic_tabla, 10);
        String unidad = ""+ tblUsuarios.getValueAt(Clic_tabla, 11);
        

        txtRut.setText(rut);
        txtPass.setText(pass);
        txtPaterno.setText(paterno);
        txtFono.setText(fono);
        txtMaterno.setText(materno);
        dtFecha.setDateFormatString(fechaI);
        txtHabilitado.setText(hab);
        txtNacionalidad.setText(nacionalidad);
        txtNombre.setText(nombre);
        txtMail.setText(mail);
        txtUnidad.setText(tipousuario);
        txtTipoUsuario.setText(unidad);
        
        

        int column = tblUsuarios.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblUsuarios.getRowHeight();

        if (row < tblUsuarios.getRowCount() && row >= 0 && column < tblUsuarios.getColumnCount() && column >= 0) {
            Object value = tblUsuarios.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("mod")) {
                    System.out.println("Click en el boton modificar");
                    //EVENTOS MODIFICAR
                    activa_boton( true, false, false);
                }
                if (boton.getName().equals("hab")) {
                    //JOptionPane.showConfirmDialog(null, "Desea eliminar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    System.out.println("Click en el boton habilitar/bloquear");
                    //EVENTOS ELIMINAR
                    activa_boton( false, true, false);
                }
            }

        }
    }//GEN-LAST:event_tblUsuariosMouseClicked

    private void btnHabilitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHabilitaActionPerformed

        int itemSeleccionado = tblUsuarios.getSelectedColumn();
        if (itemSeleccionado <= 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un usuario.", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            int fila = tblUsuarios.getSelectedRow();
            String rut = tblUsuarios.getValueAt(fila, 0).toString();
            String pass = tblUsuarios.getValueAt(fila, 1).toString();
            String nombre = tblUsuarios.getValueAt(fila, 2).toString();
            String paterno = tblUsuarios.getValueAt(fila, 3).toString();
            String materno = tblUsuarios.getValueAt(fila, 4).toString();
            String fecha_ingreso =  tblUsuarios.getValueAt(fila, 5).toString();
            String mail = tblUsuarios.getValueAt(fila, 6).toString();
            String fono = tblUsuarios.getValueAt(fila, 7).toString();
            String act = tblUsuarios.getValueAt(fila, 8).toString();
            String nacionalidad = tblUsuarios.getValueAt(fila, 9).toString();
            String id_tipoUsuario = (tblUsuarios.getValueAt(fila, 10).toString());
            String id_unidad = (tblUsuarios.getValueAt(fila, 11).toString());
            
            
            //mostrarDatos(rut,pass,nombre,paterno,materno,fecha_ingreso,mail,fono,act,nacionalidad, id_tipoUsuario, id_unidad);
            
            char act2;
            //System.out.println("valor id: " + id + " valor de activo: " + act);

            if (act.equals("Si")) {
                act2 = '0';
                
                JOptionPane.showMessageDialog(this, "Usuario cambiado a no Habilitado.");
            } else {
                act2 = '1';
                JOptionPane.showMessageDialog(this, "Usuario Habilitado.");
            }

            //System.out.println("NUEVOS -> valor id: " + id + " valor de activo: " + act);

            Database cn = new Database();
            String sql = "UPDATE usuario SET habilitado = ? WHERE rut = ?";
            PreparedStatement ps = null;
            try {
                ps = cn.getConnection().prepareStatement(sql);
                ps.setString(1, String.valueOf(act2));
                ps.setString(2, rut);
                ps.executeUpdate();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            } catch (Exception ex) {
                System.out.println(ex.getMessage());
            } finally {
                try {
                    ps.close();
                    cn = null;
                } catch (Exception ex) {
                }
            }
            
            //mostrarUsuarios();
        }


    }//GEN-LAST:event_btnHabilitaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AgregarUsuario().setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void dtFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dtFechaFocusLost

    }//GEN-LAST:event_dtFechaFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHabilita;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btn_salir;
    private com.toedter.calendar.JDateChooser dtFecha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblHabilitado;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMaterno;
    private javax.swing.JLabel lblNacionalidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPaterno;
    private javax.swing.JLabel lblTipoUsuario;
    private javax.swing.JLabel lblTituloInicial;
    private javax.swing.JLabel lblUnidad;
    private javax.swing.JTable tblUsuarios;
    private javax.swing.JTextField txtFono;
    private javax.swing.JTextField txtHabilitado;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMaterno;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPass;
    private javax.swing.JTextField txtPaterno;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTipoUsuario;
    private javax.swing.JTextField txtUnidad;
    // End of variables declaration//GEN-END:variables

    /*public void habilitacionDeTextos(boolean habili ){
        if(habili==false){
        lblTituloInicial.setText("Seleccione usuario para ver datos");
        }else{
        lblTituloInicial.setText("Datos del usuario");
        
        }
        
        lblRut.setVisible(habili);lblrut1.setVisible(habili);lblClave.setVisible(habili);lblClave1.setVisible(habili);
        lblNombre.setVisible(habili);lblNombre1.setVisible(habili);lblPaterno.setVisible(habili);lblMaterno.setVisible(habili);lblPaterno1.setVisible(habili);lblMaterno1.setVisible(habili);lblFechaIngreso.setVisible(habili);
        lblFecha1.setVisible(habili);lblMail.setVisible(habili);lblMail1.setVisible(habili);lblFono.setVisible(habili);lblFono1.setVisible(habili);
        lblHabilitado.setVisible(habili);lblHabilitado1.setVisible(habili);lblNacionalidad.setVisible(habili);lblNacionalidad1.setVisible(habili);
        lblTipo1.setVisible(habili);lblTipoUsuario.setVisible(habili);lblUnidad.setVisible(habili);lblUnidad1.setVisible(habili);
        
    }*/
    /*
    public void mostrarDatos(String rut,String pass,String nombre,String paterno,String materno,String fecha_ingreso,String mail,String fono,String act,String nacionalidad,String id_tipoUsuario,String id_unidad){
        habilitacionDeTextos(true);
        lblrut1.setText((rut));
        lblClave1.setText(pass);
        lblNombre1.setText(nombre);
        lblPaterno1.setText(paterno);
        lblMaterno1.setText(materno);
        lblFecha1.setText(fecha_ingreso);
        lblMail1.setText(mail);
        lblFono1.setText(fono);
        lblNacionalidad1.setText(nacionalidad);
        lblTipo1.setText(id_tipoUsuario);
        lblUnidad1.setText(id_unidad);
        if(act.equals("Si")){
            lblHabilitado1.setText("Habilitado");
        }else{
            lblHabilitado1.setText("No habilitado");
        }
        
    }*/
    

    
}
