/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.CRUDUnidad;
import Clases.Limpiar;
import Clases.Unidad;
import Tablas.Tabla_Unidad;
import java.awt.Color;
import java.math.BigInteger;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Esteban
 */
public class AdminUnidades extends javax.swing.JFrame {

    static Login home = new Login();

    Tabla_Unidad un = new Tabla_Unidad();
    Limpiar lim = new Limpiar();
    CRUDUnidad crud_un;
    int clic_tabla = 0;

    public AdminUnidades() {
        initComponents();
        un.visualizar_Unidad(tab_unidad);
        setExtendedState(JFrame.MAXIMIZED_HORIZ);

        setResizable(false);
        //obtenerProductos();
        activa_boton(false, false, true);
        tab_unidad.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void modificar() {
        int errores = 0;
        if (txtId.getText().equals("") || txtNombre.getText().equals("") || txtDescripción.getText().equals("")) {
            errores = errores + 1;
        }

        if (errores >= 1) {
            JOptionPane.showMessageDialog(null, "Falta información, rellene los campos", "Aviso", JOptionPane.ERROR_MESSAGE);
        } else {
            crud_un = new CRUDUnidad();
            Unidad un = new Unidad();

            un.setId_unidad(Integer.parseInt(txtId.getText()));
            un.setNombre(txtNombre.getText());
            un.setDescripcion(txtDescripción.getText());

            crud_un.Modificar_Unidad(un);
        }

    }

    public void eliminar() {
        crud_un = new CRUDUnidad();
        Unidad un = new Unidad();

        un.setId_unidad(Integer.parseInt(txtId.getText()));
        crud_un.Eliminar_Unidad(un);
    }

    public void activa_boton(boolean a2, boolean a3, boolean a4) {
        btn_modificar.setEnabled(a2);
        btn_eliminar.setEnabled(a3);
        txtId.setEnabled(a4);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab_unidad = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        lbl_rutRetail = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        lblDesc = new javax.swing.JLabel();
        txtDescripción = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Unidades");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_unidad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab_unidad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_unidad.getTableHeader().setReorderingAllowed(false);
        tab_unidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_unidadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tab_unidad);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 623, 238));

        panel.setBackground(new java.awt.Color(204, 204, 204));
        panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        panel.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 76, 164, 30));

        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });
        panel.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 45, 164, 30));

        lblId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblId.setText("ID");
        panel.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, 30));

        lblNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNombre.setText("Nombre");
        panel.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, -1, 30));

        btn_modificar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        panel.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        panel.add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, 30));

        btn_limpiar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        panel.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 120, 30));
        panel.add(lbl_rutRetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 139, -1, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        panel.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 30));

        lblDesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDesc.setText("Descripción");
        panel.add(lblDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, 30));
        panel.add(txtDescripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 108, 164, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -266, 640, 530));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 623, 240));

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tab_unidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_unidadMouseClicked
        clic_tabla = this.tab_unidad.rowAtPoint(evt.getPoint());

        String id_unidad = "" + tab_unidad.getValueAt(clic_tabla, 0);
        String nombre = "" + tab_unidad.getValueAt(clic_tabla, 1);
        String descripcion = "" + tab_unidad.getValueAt(clic_tabla, 2);

       
        txtId.setText(id_unidad);
        txtNombre.setText(nombre);
        txtDescripción.setText(descripcion);

        int column = tab_unidad.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tab_unidad.getRowHeight();

        if (row < tab_unidad.getRowCount() && row >= 0 && column < tab_unidad.getColumnCount() && column >= 0) {
            Object value = tab_unidad.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("mod")) {
                    System.out.println("Click en el boton modificar");
                    activa_boton(true, false, false);
                }
                if (boton.getName().equals("eli")) {
                    System.out.println("Click en el boton eliminar");
                    activa_boton(false, true, false);
                }
            }

        }
    }//GEN-LAST:event_tab_unidadMouseClicked

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        new Menus().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        lim.limpiar_texto(panel);
        activa_boton(false, false, true);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        int s = JOptionPane.showConfirmDialog(null, "Eliminar Unidad", "Si/no", JOptionPane.YES_NO_OPTION);
        if (s == 0) {
            eliminar();
            un.visualizar_Unidad(tab_unidad);
            activa_boton(false, false, true);
            lim.limpiar_texto(panel);
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        modificar();
        un.visualizar_Unidad(tab_unidad);
        activa_boton(false, false, true);
        lim.limpiar_texto(panel);
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    /**/
    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        /*int maximorut = 8;
        int errores = 0;
        char validarCaracter = evt.getKeyChar();
        ArrayList<Character> lista = retornarListaCaracteres();

        for (int i = 0; i < lista.size(); i++) {
            char caracter = lista.get(i);
            if (validarCaracter == caracter) {
                errores = errores + 1;
            }
        }

        if ((Character.isLetter(validarCaracter) && validarCaracter != 'k') || txt_rut.getText().length() >= maximorut || errores > 0) {
            evt.consume();
        }*/
    }//GEN-LAST:event_txtIdKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        int maximoCaracter = 29;
        char validarCaracter = evt.getKeyChar();
        if (txtNombre.getText().length() >= maximoCaracter) {
            evt.consume();

        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        /*int minimo = 4;
        if (txtId.getText().length() > 0) {
            if (txtId.getText().length() < minimo) {
                txtId.setForeground(Color.red);
                JOptionPane.showMessageDialog(null, "Ingrese id con un maximo de 4 numeros)", "Aviso", JOptionPane.ERROR_MESSAGE);
                ;
            } else {
                txtId.setForeground(Color.black);
                //rutCorrecto = true;
            }
        }*/

    }//GEN-LAST:event_txtIdFocusLost

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lbl_rutRetail;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tab_unidad;
    private javax.swing.JTextField txtDescripción;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private ArrayList<Character> retornarListaCaracteres() {
        ArrayList<Character> validaciones = new ArrayList<Character>();
        validaciones.add('.');
        validaciones.add('/');
        validaciones.add('|');
        validaciones.add('=');
        validaciones.add('?');
        validaciones.add('¿');
        validaciones.add('´');
        validaciones.add('¨');
        validaciones.add('{');
        validaciones.add('}');
        validaciones.add(';');
        validaciones.add(':');
        validaciones.add('_');
        validaciones.add('^');
        validaciones.add('-');
        validaciones.add('!');
        validaciones.add('"');
        validaciones.add('#');
        validaciones.add('$');
        validaciones.add('%');
        validaciones.add('&');
        validaciones.add('(');
        validaciones.add(')');
        validaciones.add('¡');
        validaciones.add(']');
        validaciones.add('*');
        validaciones.add('[');
        validaciones.add(',');
        validaciones.add('°');

        return validaciones;
    }

}
