/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Motivo;
import Conexion.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**904
 *
 * @author usuario
 */
public class CrearMotivo extends javax.swing.JFrame {
static Login home = new Login();
    
    
    ArrayList<Motivo> permisos = new ArrayList<Motivo>();
    Database cn;
    Connection reg;
    Connection conexion;
    Statement st;
    Database bd = new Database("");
    String ruta, nombre;
    public CrearMotivo() {
         initComponents();
         cn = new Database();
        reg = cn.getConnection();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrarMotivo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Motivo");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre Motivo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, -1, 30));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 25, 250, 30));

        btnRegistrarMotivo.setText("REGISTRAR");
        btnRegistrarMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMotivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 87, 130, 30));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 130, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VistaHermosa.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 210, 150));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 147, 60, -1));

        btnAdmin.setText("Administrar Motivo");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 87, 130, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 420, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMotivoActionPerformed
        // TODO add your handling code here:
        int ultimoId = 0;
       
        try{
            ArrayList<Object> motivos = new ArrayList<Object>();
            PreparedStatement coleccionMotivo = null;
            coleccionMotivo = reg.prepareStatement("SELECT * FROM motivo");
            PreparedStatement pst = null;
            String descripcion=txtDescripcion.getText();
            ResultSet lista = coleccionMotivo.executeQuery();
           

            while (lista.next()) //recorre
            {
                if (ultimoId < lista.getInt(1)) {
                    ultimoId = lista.getInt(1);
                }
            }
            ultimoId = ultimoId + 101;
            pst = reg.prepareStatement("INSERT INTO motivo VALUES(?,?)");
            if (ultimoId == 0) {
                ultimoId = 1;
            }
            pst.setInt(1, ultimoId);
            pst.setString(2, descripcion);
            
            pst.executeUpdate();
             JOptionPane.showMessageDialog(this, "Motivo Registrado Correctamente.");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "ERROR." + e, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegistrarMotivoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:

        new Menus().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        new AdminMotivos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnRegistrarMotivo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
