/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Clases.Unidad;
import Conexion.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class CrearUnidad extends javax.swing.JFrame {
static Login home = new Login();
    
 
    ArrayList<Unidad> unidades = new ArrayList<Unidad>();
    Database cn;
    Connection reg;
    //
    Connection conexion;
    Statement st;
    Database bd = new Database("");
    String ruta, nombre;
    public CrearUnidad() {
        initComponents();
        cn = new Database();
        reg = cn.getConnection();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        btnRegistrarUnidad = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        btnAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Unidad");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        jLabel3.setText("DESCRIPCION");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 230, 30));
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 55, 230, 60));

        btnRegistrarUnidad.setText("REGISTRAR");
        btnRegistrarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarUnidadActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 140, 30));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 140, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VistaHermosa.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 223, 148));

        btnAdmin.setText("Administrar Unidades");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registro.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 480, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarUnidadActionPerformed
        // TODO add your handling code here:
      int ultimoId = 0;
      //FileInputStream fis = null;
      try{
          ArrayList<Object> unidades = new ArrayList<Object>();
          PreparedStatement coleccionUnidad = null;
          coleccionUnidad = reg.prepareStatement("SELECT * FROM unidad");
          PreparedStatement pst = null;
          String nombre=txtNombre.getText();
          String descrip=txtDescripcion.getText();
          ResultSet lista = coleccionUnidad.executeQuery();
          
      while (lista.next()) //recorre
                {
                    if (ultimoId < lista.getInt(1)) {
                        ultimoId = lista.getInt(1);
                    }
                }
                ultimoId = ultimoId + 1;
                 pst = reg.prepareStatement("INSERT INTO unidad VALUES(?,?,?)");
                if (ultimoId == 0) {
                    ultimoId = 1;
                }
                pst.setInt(1, ultimoId);
                pst.setString(2, nombre);
                pst.setString(3, descrip);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Unidad Registrada Correctamente.");
      }catch(Exception e){
           JOptionPane.showMessageDialog(this, "ERROR." + e, "ERROR", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_btnRegistrarUnidadActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
     
        new Menus().setVisible(true);
           this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        new AdminUnidades().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnRegistrarUnidad;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
